config/routes.rb
Environmentalist::Application.routes.draw do
  resources :environments do
    member do
      post 'reserve'
      post 'release'
    end
  end
  root :to => 'environments#index'

end

app/models/environment.rb
class Environment < ActiveRecord::Base
  attr_accessible :name, :reserved_by
  validates_presence_of :name, :on => :create

  def as_json(options={})
    {
      :id => id,
      :name => name,
      :reserved_by => reserved_by.blank? ? ' ' : reserved_by,
      :updated_at => updated_at
    }
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/environments_controller.rb
class EnvironmentsController < ApplicationController
  def new
    @environment = Environment.new
  end

  def create
    @environment = Environment.new(params[:environment])

    if @environment.save
      redirect_to environments_url
    else
      render :new
    end
  end

  def index
    @environments = Environment.all

    respond_to do |format|
      format.html
      format.json { render :json => @environments }
    end
  end

  def show
    environment = Environment.find(params[:id])

    respond_to do |format|
      format.html { redirect_to environments_url}
      format.json { render :json => environment }
    end
  end

  def reserve
    environment = Environment.find(params[:id])

    environment.update_attributes(:reserved_by => params[:environment][:reserved_by])

    respond_to do |format|
      format.html { redirect_to environments_url }
      format.json { render :json => environment }
    end
  end

  def release
    environment = Environment.find(params[:id])

    environment.update_attributes(:reserved_by => '')

    respond_to do |format|
      format.html { redirect_to environments_url }
      format.json { render :json => environment }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/environments/_environment.html.erb
<tr>
  <td><%= environment.name %></td>
  <td><%= environment.updated_at %></td>
</tr>

app/views/environments/index.html.erb
<h1>Environments</h1>

<table class="table table-striped table-condensed">
  <thead>
    <tr>
      <th>Name</th>
      <th>Updated At</th>
    </tr>
  </thead>
  <tbody>
    <%= render @environments %>
  </tbody>
</table>
<p><%= link_to "New", new_environment_url, :class => "btn btn-primary" %></p>

app/views/environments/new.html.erb
<%= form_for @environment, {:html => {:class => "form-horizontal"}} do |f| %>
  <fieldset>
    <legend>New Environment</legend>
    <div class="control-group">
      <%= f.label :name, 'Name', :class => "control-label" %>
      <div class="controls">
        <%= f.text_field :name%>
      </div>
    </div>
    <div class="form-actions">
      <%= f.submit :class => "btn btn-primary" %>
    </div>
  </fieldset>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Environmentalist" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <link href="images/favicon.ico" rel="shortcut icon">
    <link href="images/apple-touch-icon.png" rel="apple-touch-icon">
    <link href="images/apple-touch-icon-72x72.png" rel="apple-touch-icon" sizes="72x72">
    <link href="images/apple-touch-icon-114x114.png" rel="apple-touch-icon" sizes="114x114">
  </head>
  <body>

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container-fluid">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="#">Environmentalist</a>
          <div class="container-fluid nav-collapse">
            <ul class="nav">
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container-fluid">
      <div class="row-fluid">
        <div class="span9">
          <div class="span12">
            <%= yield %>
          </div>
        </div><!--/row-->

        <footer>
        </footer>

      </div> <!-- /container -->

      <!-- Javascripts
      ================================================== -->
      <!-- Placed at the end of the document so the pages load faster -->
      <%= javascript_include_tag "application" %>

    </body>
  </html>